### ISSUE TITLE
Create a CONTRIBUTORS.md File

### ISSUE THREAD

**Issue by evrentan** [evrentan/qr-code-generator-backend#13]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Create a CONTRIBUTORS.md File instead of listing contributors under Credits section in [README](https://github.com/evrentan/qr-code-generator-backend/blob/main/README.md) file.

Put a link reference to the new file within Credits section.

**Describe alternatives you've considered**
N/A.

**Additional context**
Also, if you are a new contributor, pls do not forget to put your name in the list :)

**Comment by Rohit-R2000** [comment]
please assign this to me

**Comment by evrentan** [comment]
> please assign this to me

Hi @Rohit-R2000,
Assigned to you. Thanks.

**Comment by evrentan** [comment]
Finished with the [PR](https://github.com/evrentan/qr-code-generator-backend/pull/14).
