### ISSUE TITLE
[Bug]: Minor refactor suggestions regarding Controller method arguments

### ISSUE THREAD

**Issue by M2U7BF** [evrentan/qr-code-generator-backend#35]
Hi! I am using your application and I am reporting that I have come up with a minor refactor proposal.
<br>
**Describe the bug**
◆ What kind of bug is it?
This is a bug that the Controller allows requests with empty characters.

◆ What is the problem?
When the Controller receive a request with an empty string, it throw a 500 internal server error,
and I wonder if this will cause problems when used with some services.

◆ proposal
Improve parameter validation to return with 400 errors.

I'm considering the idea of using `@NotEmpty` annotation instead of `@NotNull`.
https://github.com/evrentan/qr-code-generator-backend/blob/cf7ff278b6ba8bff697563358e302aa452f60ab0/src/main/java/evrentan/qrcodegenerator/qrcodegeneratorbackend/controller/QrCodeController.java#L73
https://github.com/evrentan/qr-code-generator-backend/blob/cf7ff278b6ba8bff697563358e302aa452f60ab0/src/main/java/evrentan/qrcodegenerator/qrcodegeneratorbackend/controller/QrCodeController.java#L118
However, when I tried it locally, it didn't work...so I'm stumped...
<br>

**To Reproduce**
1. Launch the app locally
2. Send a request with an empty string to the appropriate endpoint with curl or postman
![image](https://github.com/evrentan/qr-code-generator-backend/assets/98495911/4eac6d20-af8d-406e-a449-80caa9f31093)
3. It throw a 500 internal server error
![image](https://github.com/evrentan/qr-code-generator-backend/assets/98495911/0119e751-3754-4c79-9938-3a91c9caeda2)
<br>

**Expected behavior**
When a request with an empty string is received, it should be returned with a 400 bad request error.
<br>

**Desktop (please complete the following information):**
 - OS: Windows11
 - Version: 22H2
<br>

**Additional context**
Thank you for creating such a useful application!

**Comment by evrentan** [comment]
Thanks @M2U7BF for submitting the bug. I will look at it 👍🏻

**Comment by evrentan** [comment]
@M2U7BF , thanks again for the finding. I have just fixed it and release the latest version with [v1.0.0](https://github.com/evrentan/qr-code-generator-backend/releases/tag/v1.0.0).

Happy coding and thanks for using my open source app.
