### ISSUE TITLE
Implement a Custom Exception Management

### ISSUE THREAD

**Issue by evrentan** [evrentan/qr-code-generator-backend#7]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Implement a Custom Exception Management class in order to use it while handling exceptions throughout the code base.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nmarulo** [comment]
Hello @evrentan 👋, please, could you explain me a little more what you want to do? you could try it

**Comment by evrentan** [comment]
Hi @nmarulo 👋🏻,
The ultimate goal is to implement a global custom exception handler class in order to manage exceptions in a centralized way. Like the WriterException, IOException exceptions that are catched in impl class.

You can check one of my prev example from the below repo;

https://github.com/evrentan/spring-boot-project-example/blob/main/src/main/java/evrentan/examples/springbootprojectexample/exception/GlobalRestExceptionHandler.java

**Comment by nmarulo** [comment]
@evrentan 
Ok, using `@RestControllerAdvice` I understand.
The object with the custom error, the same?

**Comment by evrentan** [comment]
Yes, it can be same. The later task will implement ResourceBundles and chaning the messages according to preferred language in the message (i.e., for example an attribute in the header).

Do you want to take this issue?

**Comment by nmarulo** [comment]
> Do you want to take this issue?

ok, I will do it 👍

**Comment by evrentan** [comment]
Just assigned to you. Thanks :)
